apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels:
    app.kubernetes.io/name: github-webhook-ingress
    app.kubernetes.io/part-of: cortex-cicd
  name: github-webhook-ingress
  namespace: cortex-cicd
spec:
  ingressClassName: nginx
  rules:
  - host: tekton-webhooks.cortex-io.dev
    http:
      paths:
      - backend:
          service:
            name: el-github-webhook-listener
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tekton-webhooks.cortex-io.dev
    secretName: tekton-webhooks-tls
