apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  labels:
    app: mcp-server
  name: mcp-server-ingress
  namespace: cortex-knowledge
spec:
  ingressClassName: traefik
  rules:
  - host: knowledge-mcp.cortex-io.dev
    http:
      paths:
      - backend:
          service:
            name: mcp-server
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - knowledge-mcp.cortex-io.dev
    secretName: knowledge-mcp-tls
