apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  labels:
    app: cortex-queue-worker
    component: task-processor
  name: cortex-queue-worker
  namespace: cortex
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cortex-queue-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-01-05T07:18:56-06:00'
      creationTimestamp: null
      labels:
        app: cortex-queue-worker
        component: task-processor
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-queue.cortex.svc.cluster.local
        - name: REDIS_PORT
          value: '6379'
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              key: anthropic-api-key
              name: cortex-secrets
        - name: IDLE_TIMEOUT_MS
          value: '300000'
        - name: TASKS_DIR
          value: /app/tasks
        image: 10.43.170.72:5000/cortex-queue-worker:latest
        imagePullPolicy: Always
        name: worker
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/tasks
          name: tasks-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tasks-storage
