apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkmk-ingress
  namespace: checkmk
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  labels:
    app: checkmk
spec:
  ingressClassName: traefik
  rules:
  - host: checkmk.ry-ops.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: checkmk
            port:
              number: 5000
  tls:
  - hosts:
    - checkmk.ry-ops.dev
    secretName: checkmk-tls
