apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  labels:
    app: langflow-chat-mcp-server
  name: langflow-chat-mcp-ingress
  namespace: cortex-system
spec:
  ingressClassName: traefik
  rules:
  - host: langflow-chat-mcp.ry-ops.dev
    http:
      paths:
      - backend:
          service:
            name: langflow-chat-mcp-server
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - langflow-chat-mcp.ry-ops.dev
    secretName: langflow-chat-mcp-tls
