apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  labels:
    app: n8n-mcp-server
  name: n8n-mcp-ingress
  namespace: cortex-system
spec:
  ingressClassName: traefik
  rules:
  - host: n8n-mcp.cortex-io.dev
    http:
      paths:
      - backend:
          service:
            name: n8n-mcp-server
            port:
              number: 3002
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - n8n-mcp.cortex-io.dev
    secretName: n8n-mcp-tls
