apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: sandfly-transport@kubernetescrd
  labels:
    app: sandfly-web
  name: sandfly-ingress
  namespace: cortex-system
spec:
  ingressClassName: traefik
  rules:
  - host: sandfly.ry-ops.dev
    http:
      paths:
      - backend:
          service:
            name: sandfly-web
            port:
              number: 443
        path: /
        pathType: Prefix
