apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: falco
    meta.helm.sh/release-namespace: cortex-security
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/version: 2.31.1
    helm.sh/chart: falcosidekick-0.11.1
  name: falco-falcosidekick-ui
  namespace: cortex-security
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: falco
      app.kubernetes.io/name: falcosidekick
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ui
        app.kubernetes.io/instance: falco
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: falcosidekick
        app.kubernetes.io/part-of: falcosidekick
        app.kubernetes.io/version: 2.31.1
        helm.sh/chart: falcosidekick-0.11.1
    spec:
      containers:
      - args:
        - -r
        - falco-falcosidekick-ui-redis:6379
        - -l
        - info
        envFrom:
        - secretRef:
            name: falco-falcosidekick-ui
        image: docker.io/falcosecurity/falcosidekick-ui:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: falcosidekick-ui
        ports:
        - containerPort: 2802
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - /scripts/ping-redis.sh
        envFrom:
        - secretRef:
            name: falco-falcosidekick-ui
        image: docker.io/redis/redis-stack:7.2.0-v11
        imagePullPolicy: IfNotPresent
        name: wait-redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts/ping-redis.sh
          name: scripts
          subPath: ping-redis.sh
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1234
        runAsUser: 1234
      serviceAccount: falco-falcosidekick-ui
      serviceAccountName: falco-falcosidekick-ui
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 365
          items:
          - key: ping-redis.sh
            path: ping-redis.sh
          name: falco-falcosidekick-ui-redis
        name: scripts
