apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cortex-proxmox-fabric
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: proxmox-activator
            path: apps/cortex-proxmox-fabric/proxmox-activator
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/cortex-io/cortex-gitops.git
        targetRevision: main
        path: '{{ .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: cortex-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
