apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.145.200"],"port":443,"protocol":"HTTPS","serviceName":"cortex-chat:grafana-pdf-service","ingressName":"cortex-chat:cortex-chat","hostname":"chat.ry-ops.dev","path":"/api/report","allNodes":false},{"addresses":["10.88.145.200"],"port":443,"protocol":"HTTPS","serviceName":"cortex-chat:cortex-chat","ingressName":"cortex-chat:cortex-chat","hostname":"chat.ry-ops.dev","path":"/","allNodes":false}]'
  name: cortex-chat
  namespace: cortex-chat
spec:
  ingressClassName: traefik
  rules:
  - host: chat.ry-ops.dev
    http:
      paths:
      - backend:
          service:
            name: grafana-pdf-service
            port:
              number: 3001
        path: /api/report
        pathType: Prefix
      - backend:
          service:
            name: chat-activator
            port:
              number: 8080
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: cortex-chat
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - chat.ry-ops.dev
    secretName: chat-ry-ops-dev-tls
