apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cortex-chat:apps/Deployment:cortex-chat/cortex-chat-proxy
    deployment.kubernetes.io/revision: '6'
  name: cortex-chat-proxy
  namespace: cortex-chat
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cortex-chat-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-12-25T10:28:02-06:00'
      creationTimestamp: null
      labels:
        app: cortex-chat-proxy
    spec:
      containers:
      - command:
        - node
        - /app/proxy.js
        env:
        - name: CORTEX_MCP_URL
          value: http://cortex-orchestrator.cortex.svc.cluster.local:8000
        image: node:20-alpine
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app
          name: proxy-script
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: cortex-chat-proxy
        name: proxy-script
