apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    field.cattle.io/publicEndpoints: '[{"addresses":["10.88.145.200"],"port":443,"protocol":"HTTPS","serviceName":"cortex-chat:grafana-pdf-service","ingressName":"cortex-chat:grafana-pdf-service","hostname":"cortex-reports.ry-ops.dev","path":"/","allNodes":false},{"addresses":["10.88.145.200"],"port":443,"protocol":"HTTPS","serviceName":"cortex-chat:grafana-pdf-service","ingressName":"cortex-chat:cortex-chat","hostname":"chat.ry-ops.dev","path":"/api/report","allNodes":false}]'
  name: grafana-pdf-service
  namespace: cortex-chat
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana-pdf-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-01-08T19:30:25-06:00'
      creationTimestamp: null
      labels:
        app: grafana-pdf-service
    spec:
      containers:
      - command:
        - node
        - /app/server.js
        image: node:18-alpine
        imagePullPolicy: IfNotPresent
        name: service
        ports:
        - containerPort: 3001
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app
          name: app
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - 'cp /config/* /app/

          cd /app

          npm install --production --no-package-lock

          '
        image: node:18-alpine
        imagePullPolicy: IfNotPresent
        name: setup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /app
          name: app
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: grafana-pdf-service-code
        name: config
      - emptyDir: {}
        name: app
